
platform:
  - x64

install:

  # Take a look at the environment
  - set "PATH=C:\msys64\usr\bin;C:\msys64\mingw64\bin;%PATH%"

  - C:\msys64\usr\bin\bash -lc ""
  - C:\msys64\usr\bin\bash -lc "pacman --version"
  # Switch from SF to msys2.org (default, much faster)
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm --sync pacman-mirrors"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S autoconf automake bison flex perl perl-XML-LibXML"

build_script:
  ## Notes
  #  * The "exec 0</dev/null" opens a dummy file descriptor to fix error: ./configure: line 560: 0: Bad file descriptor

  ## Build
  - bash -lc "exec 0</dev/null && cd $APPVEYOR_BUILD_FOLDER && ./bootstrap.sh"
  - bash -lc "exec 0</dev/null && cd $APPVEYOR_BUILD_FOLDER && ./configure --enable-maintainer-mode"
  - bash -lc "exec 0</dev/null && cd $APPVEYOR_BUILD_FOLDER && make install"

  - bash -lc "exec 0</dev/null && admsXml -v"
