language: c

compiler:
  - gcc
  - clang

before_install:

  - sudo apt-get install automake libtool flex
  - sudo apt-get install libxml2 libxml2-dev

  # configure cpan, no waiting for user input
  - (echo y;echo o conf prerequisites_policy follow;echo o conf commit)| sudo cpan
  - sudo cpan -i XML::LibXML

script:
  - bison --version
  - flex --version
  - $CC --version
  - which $CC
  # workaround clang not system wide, fail on sudo make install
  - export CC=`which $CC`

  - ./bootstrap.sh
  - ./configure --enable-maintainer-mode --prefix=/usr
  - make
  - sudo make install

  # test
  - admsXml -h

